# Generated by Django 5.1.7 on 2025-03-25 15:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pokemon_entities', '0008_pokemon_evolved_from_pokemon_evolved_to'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pokemon',
            name='evolved_from',
        ),
        migrations.RemoveField(
            model_name='pokemon',
            name='evolved_to',
        ),
        migrations.AddField(
            model_name='pokemon',
            name='previous_evolution',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='next_evolutions', to='pokemon_entities.pokemon', verbose_name='Из кого эволюционирует'),
        ),
    ]
